name: Import Attendance

on:
  workflow_dispatch:
  schedule:
    - cron: '59 11 * * 0'   # Sunday 11:59
    - cron: '0 14 * * 0'    # Sunday 14:00
    - cron: '0 18 * * 0'    # Sunday 18:00
    - cron: '0 20 * * 0'    # Sunday 20:00


jobs:
  run-attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver || \
          sudo apt-get install -y chromium chromium-driver
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          # Install Google Chrome
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          # Install ChromeDriver
          CHROME_VERSION=$(google-chrome --version | cut -d " " -f3 | cut -d "." -f1)
          DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip -q chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          

      - name: Run CSV Drive Bot
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: python csvdrivebot.py

      - name: Run Import Attendance
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: python importattendance.py

      - name: Upload failed entries CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failed-entries
          path: failed_entries*.csv

      - name: Upload Selenium screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: "*.png"




