name: Import Attendance

on:
  workflow_dispatch:
  schedule:
    - cron: '59 11 * * 0'   # Sunday 11:59
    - cron: '0 14 * * 0'    # Sunday 14:00
    - cron: '0 18 * * 0'    # Sunday 18:00
    - cron: '0 20 * * 0'    # Sunday 20:00


jobs:
  run-attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v2

      - name: Set up ChromeDriver
        uses: browser-actions/setup-chromedriver@v1
        with:
          version: latest
            
      - name: Run CSV Drive Bot
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: python csvdrivebot.py

      - name: Run Import Attendance
        run: python importattendance.py

      - name: Upload failed entries CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failed-entries
          path: "failed_entries*.csv"

      - name: Upload Selenium screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: "screenshot*.png"






